version: "3.9"

services:
  db:
    container_name: db
    build:
      context: ./mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - /home/node_modules
  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
    volumes:
      - ./symfony:/var/www/symfony:cached
    depends_on:
      - db

  app_test:
    container_name: app_test
    image: nginx:1.19
    ports:
      - "3333:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/app_test.conf:/etc/nginx/conf.d/default.conf

  app_dev:
    container_name: app_dev
    image: nginx:1.19
    ports:
      - "4444:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/app_dev.conf:/etc/nginx/conf.d/default.conf

  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher:0.8
    ports:
      - "1080:1080"

  cypress:
    container_name: cypress
    build:
      context: ./e2e
    volumes:
      - ./e2e:/home/e2e/tests:cached
      - /home/e2e/tests/node_modules
volumes:
  db:
