version: "3.9"

services:
  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ~/.config/gcloud:/.config/gcloud

  app_test:
    container_name: app_test
    image: nginx:1.19
    ports:
      - "3333:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/app_test.conf:/etc/nginx/conf.d/default.conf

  app_dev:
    container_name: app_dev
    image: nginx:1.19
    ports:
      - "4444:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/app_dev.conf:/etc/nginx/conf.d/default.conf

  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher:0.8
    ports:
      - "1080:1080"

  cypress:
    container_name: cypress
    build:
      context: ./e2e
    volumes:
      - ./e2e:/home/e2e/tests:cached
      - /home/e2e/tests/node_modules
