services:
  db:
    container_name: db
    image: 'mysql:8.0.36-debian'
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ~/.config/gcloud:/.config/gcloud
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19
    ports:
      - "4444:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app_dev.conf:/etc/nginx/conf.d/default.conf

  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher:0.8
    ports:
      - "1080:1080"
volumes:
  db:
