api_platform:
  title: Breizh Blok
  version: 1.0.0
  use_symfony_listeners: true
  serializer:
    hydra_prefix: true
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header