auth0:
  sdk:
    domain: "%env(trim:string:AUTH0_DOMAIN)%"
    client_id: "%env(trim:string:AUTH0_CLIENT_ID)%"
    client_secret: "%env(trim:string:AUTH0_CLIENT_SECRET)%"
    cookie_secret: "%kernel.secret%"

    audiences:
      - "%env(trim:string:AUTH0_API_AUDIENCE)%"

    scopes:
      - openid
      - profile
      - email
      - offline_access

    token_cache: auth0_token_cache
    management_token_cache: auth0_management_token_cache