security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    auth0_provider:
      id: Auth0\Symfony\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/admin
      lazy: true
      provider: app_user_provider
      form_login:
        # form_login is not used. This is used only to redirect not authenticated user to login link page
        enable_csrf: true
        login_path: login
        check_path: not_existing_route
        default_target_path: admin
        always_use_default_target_path: true
      login_link:
        check_route: login_check
        signature_properties: ['id']
        success_handler: App\Security\AuthenticationSuccessHandler

      logout:
        path: app_logout
    api:
      pattern: ^/
      stateless: true
      provider: auth0_provider
      custom_authenticators:
        - auth0.authorizer


  access_control:
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_CONTRIBUTOR }

  access_decision_manager:
    strategy: unanimous

  role_hierarchy:
    ROLE_CONTRIBUTOR: ROLE_USER
    ROLE_ADMIN: ROLE_CONTRIBUTOR
    ROLE_SUPER_ADMIN: ROLE_ADMIN
