vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    media:
      uri_prefix: "%general_images_relative_path%"
      upload_destination: "%general_images_absolute_path%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
        options: { chars_per_dir: 3, dirs: 1 }
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
