vich_uploader:
  db_driver: orm
  storage: flysystem
  metadata:
    type: attribute

  mappings:
    media:
      uri_prefix: ''
      upload_destination: pictures.storage
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
