when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true
        faker:
            locale: fr_FR
        make_factory:
            default_namespace:    DataFixtures\Factory
            add_hints: false
        make_story:
            default_namespace:    DataFixtures\Story

when@test: *dev
