monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface

    main:
      type: rotating_file
      action_level: error
      # excluded_404s:
      # regex: exclude all 404 errors from the logs
      # - ^/
      max_files: 10
      file_permission: 0777
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
