sentry:
  dsn: '%env(SENTRY_DSN)%'
  # https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
  register_error_listener: false
  register_error_handler: false
  # https://docs.sentry.io/platforms/php/guides/symfony/performance/instrumentation/automatic-instrumentation/
  tracing:
    enabled: false