sentry:
  dsn: '%env(SENTRY_DSN)%'
  register_error_listener: false
  register_error_handler: false
  options:
    traces_sample_rate: 1.0
  tracing:
    enabled: true
    dbal:
      enabled: true
    cache:
      enabled: true
    twig:
      enabled: false
    http_client:
      enabled: true